import os

POSTGRES_SERVER = os.getenv("POSTGRES_SERVER")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWD = os.getenv("POSTGRES_PASSWD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
DATABASE_URI = (
    f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWD}@{POSTGRES_SERVER}/{POSTGRES_DB}"
)
